### ISSUE TITLE
There should be an option for a set number of loops when "Repeat" is turned on in Playlist

### ISSUE THREAD

**Issue by SSBMTonberry** [SSBMTonberry/emu-jukebox#52]
Right now you can either make a track det played once, or just loop forever (until you choose to skip the song). Due to some tracks being naturally short, one might want to make it last longer, by maybe having it play 2 or 3 times before going to the next song. This should be a simple input-textbox(int). Value 0 should make it repeat like before (unlimited number of times until you've chosen to skip the track), and else it should say how many times you want the track repeated.

**Comment by AlexanderBrevig** [comment]
I would suggest that we add a `bool ebox::Hotkeys::isGlobalHotkeyPressed(ebox::Hotkeys::ProgramHotkey hotkey)` which does not check `m_isActive`. This should work as your Hotkey already uses `sf::Keyboard::isKeyPressed` [which is not dependent on the Window events](https://github.com/SSBMTonberry/emu-jukebox/blob/2c1912ae8ac03535260a9cef65c6847f3e5c494f/external_libs/include/SFML/Window/Keyboard.hpp#L204) and thus will work even if window is minimized.

**Comment by SSBMTonberry** [comment]
@AlexanderBrevig : Did you mean to answer to issue #53? If so, I agree that this is how it should be done, and is how I intend to implement it. I knew that I could have global hotkey on Linux, but wasn't sure if that was the case for all OS-es, but it seems like this luckily is the case, based on the doc you are linking to 😄  Implementing the global hotkeys themselves will not take much time, but I think it is important to also be able to define these hotkeys yourself, or at the very least be able to turn the feature on/off.

**Comment by AlexanderBrevig** [comment]
damnit... yes I did - evidently opening more tabs was not a good idea
excellent points though.

**Comment by SSBMTonberry** [comment]
This can now be done via preferences.
