### ISSUE TITLE
Misleading error log message when removing item from "Files"

### ISSUE THREAD

**Issue by SSBMTonberry** [SSBMTonberry/emu-jukebox#6]
- Right-click and choose remove on something in the "Files" window. You see a message saying "EmuStream() - Couldn't open file"

![image](https://user-images.githubusercontent.com/26206421/53832566-e57f3f00-3f86-11e9-9e77-0a6a7bb089d2.png)

**Comment by AlexanderBrevig** [comment]
Before [Fixes 6 erase outside iterator loop](https://github.com/SSBMTonberry/emu-jukebox/pull/42) this craches on windows.

**Comment by SSBMTonberry** [comment]
Confirmed! Well done, @AlexanderBrevig 😄
